### ISSUE TITLE
"undefined" displayed next to usernames

### ISSUE THREAD

**Issue by ashrafchowdury** [pezzolabs/pezzo#275] opened 2023-12-11 06:54 UTC
### Report

**The word "undefined" is displayed next to the username in various locations throughout the application** (e.g., user menu, profile page). This is unexpected and confusing for users.

### Expected behavior

The word "undefined" is not being displayed at all. 

### Steps to reproduce the problem

1. We have to add a `conditional statement` if there is a last-name component available.

### Logs (if applicable)

![image](https://github.com/pezzolabs/pezzo/assets/87828904/b94576f2-7c95-4c99-905f-78e877007f96)

![image](https://github.com/pezzolabs/pezzo/assets/87828904/0df2ffed-84a9-4d78-bf18-9d6bbfeb5359)

### Pezzo version

latest one

### How do you use Pezzo?

Pezzo Cloud

**Comment by the-land-mine** [comment] 2023-12-19 12:37
can I take this issue?

**Comment by arielweinberger** [comment] 2023-12-19 13:43
Absolutely @the-land-mine - let me know if you need assistance.

**Comment by the-land-mine** [comment] 2024-01-02 09:08
@arielweinberger Sorry for the late response. I think this issue has been fixed already in some other PRs. this issue doesn't exist now in the current `main`. I was not able to reproduce the issue. I think you can close this issue now. I will look for some other issues which I can help. Thanks

**Closed** 2024-01-03 04:41 UTC
Labels: bug
