### ISSUE TITLE
Different prompt in test result prompt and given input

### ISSUE THREAD

**Issue by pallasite99** [pezzolabs/pezzo#19] opened 2023-05-10 05:54 UTC
![image](https://github.com/pezzolabs/pezzo/assets/26508636/08f39dcd-e902-4496-8d63-4c997b47bc6a)

does not affect functionality, but maybe something in cache causes this.

**Comment by arielweinberger** [comment] 2023-05-10 07:06
Thanks Salil. Indeed this is a bug.

**Comment by arielweinberger** [comment] 2023-05-10 10:55
@pallasite99 Can you please provide steps to reproduce? I recon there was an issue there, but I cannot reproduce it now. Thanks!

**Comment by pallasite99** [comment] 2023-05-10 11:15
Yup. 
Basically -
1. Input test prompt after going to console
2. After viewing result navigate back to input second prompt
3. After step 2 click on test and you’ll see the earlier prompt instead of newer prompt

**Comment by arielweinberger** [comment] 2023-05-15 21:22
Closing it for now as I cannot reproduce.

**Closed** 2023-05-23 11:46 UTC
Labels: bug, good first issue
